### ISSUE TITLE
Fooyin Does Not Read Meta Tag that Other Apps See

### ISSUE THREAD

**Issue by Alex9001** [fooyin/fooyin#115]
Fooyin Version: 0.4.3
Artix Linux

Issue:
Files with RATING field should show in RATINGS column (#113) when loaded into playlist but do not.

Expected operation:
Load files with RATING field into playlist. Rating column displays ratings.

Actual operation:
Load files with RATING field into playlist. Ratings column fails to display.

Further info:

Sample file: https://www.dropbox.com/scl/fi/ferzofw3fqvyd0gt2s3lq/07Nature.wav?rlkey=c2751m2se21w410qvjkkgfcrs&st=91f0pwq1&dl=0

Left: Kid3 Center: Fooyin Right: Foobar2000
![image](https://github.com/ludouzi/fooyin/assets/2770710/375141cd-bf28-46da-8667-ca29e092a584)

Strangely enough, adding the RATING field in Fooyin makes it appear.

**Comment by ludouzi** [comment]
This might be because I'm in the process of explicitly handling the rating tag in order to eventually make it editable in the playlist, but in doing so it's excluded from the list of 'extra' tags that get stored. This should only be affecting the rating tag, so I'm going to go ahead and add full rating support to fix this.

**Comment by ludouzi** [comment]
Ratings are now properly handled (displaying and editing) so I'll consider this resolved. There are many different scales used by different players for ratings, so feel free to reopen this if you encounter any further issues.

**Comment by mallniya** [comment]
Hello, I'm still concerned about RATING tag.

My case is slightly different than @Alex9001 (I use 10-grade rating system), though idea is the same: I use RATING tag merely as another not standardized tag and expect any tag viewer/editor to just have access to any key one wants. It's really handy to have it agnostically recognized, so in a case of moving to another player (which I really want now when I've found fooyin) I expect it to just work with existing tags. It just works with deadbeef for an instance and as far as I remember foobar2000 doesn't restrict direct access to tags through `$meta()`). Sadly for me, fooyin treats this tag in a special way, though I see what was the intentions of making this tag special.
So now I see the following behavior: `$meta(RATING)` shows nothing and `%RATING%` shows decimals. Latter is just a special logic of fooyin, which I just don't see fit for me, so I just ignore it. But inability to just show a value of RATING tag for me is just a showstopper and I think it contradicts tweakable spirit of fooyin and foobar2000.

So my request is simple: please don't restrict `$meta()` in any way and let the user decide what to do.

**Comment by ludouzi** [comment]
fooyin stores the rating internally as a float in the range 0.0-1.0 to cover all possible rating systems. `%rating%` will return this, while `%rating_stars%` will return this value mapped to star rating (0-10). 

On a related note, the arguments for `$meta()` and `$info()` are currently case sensitive for lower case. It'll probably be best to change that.

**Comment by mallniya** [comment]
> while %rating_stars% will return this value mapped to star rating (0-10).

In my case it doesn't show anything, though frankly I don't need this. What I miss is a direct access to tags without any special logic. Should I create separate issue for this? Or this contradicts architecture of tag handling in fooyin?

> On a related note, the arguments for $meta() and $info() are currently case sensitive for lower case. It'll probably be best to change that.

Can't get how this relate to the topic. Just for clarification: other custom tags do with `$meta()` just ok.

**Comment by ludouzi** [comment]
> Or this contradicts architecture of tag handling in fooyin?

No, I agree that you should be able to access the raw value of any tag. The main problem is that because rating is mapped to a float when reading, the raw value isn't stored in the database so it can be easily accessed. 

I suppose we could store the raw tag value as well as the value as a float. Though that opens up potential issues when using the built-in rating editor, as it would only be able to update the float value. I guess that'll be up to the user.

> Can't get how this relate to the topic

Before https://github.com/fooyin/fooyin/commit/2bf4cf9059fd7b7859a6b2ee347f65245b12803d, `$meta(RATING)` wouldn't return anything but `$meta(rating)` should.
