### ISSUE TITLE
[Feature Request] Use different iconography for repeat options

### ISSUE THREAD

**Issue by dalto8** [fooyin/fooyin#131]
Currently, the icon for repeat track and repeat playlist are the same since a single icon is used that only has two states.  This means there is no way to visually see which repeat mode you are in by looking at the application.  You either need to click the icon and view the text in the panel that pops up or wait for the track to end and see what happens.

It would be great if there was an obvious visual indicator of the state that you could see at a glance.

**Comment by ludouzi** [comment]
In the early stages of development, fooyin actually had a separate icon for repeat track. This was later removed when I added the option to use the system icons and followed the [Icon Naming Specification](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html), as otherwise that icon would be the odd one out.

As a compromise, I could add that icon back and only use it if the user is using one of the built-in icon themes.

**Comment by dalto8** [comment]
Thanks!
