### ISSUE TITLE
CUE files causing double song entries

### ISSUE THREAD

**Issue by ripdog** [fooyin/fooyin#139]
Hello, I've found another issue with CUE support. 

![image](https://github.com/ludouzi/fooyin/assets/174944/bbb79210-f007-4155-a307-a835ddecc6eb)

Simply, there are two versions of each track, one from the CUE and one direct from the file. It's entirely unclear to the user why this happened, also how to fix it. Honestly, I'm happy to just nuke all my CUE files (I honestly don't understand their purpose, the only thing they ever do is confuse music players), but that hardly seems like an ideal solution for Fooyin.

At least an option to disable adding CUE files to the library should be available, but I wonder if CUE files could be made actually useful by fooyin ignoring raw music files which have a CUE file reference them? As I'm unsure what CUE files are actually for (apart from splitting multi-track files, which are rare), I don't know if this is a good option. But I think something should be done about this.

**Comment by ludouzi** [comment]
I managed to reproduce this for a few of my albums. It only occurs when refreshing the library on startup (or manually), and the duplicate tracks are not saved to the database.

When scanning library directories, fooyin groups all of the CUE files and all of the audio files separately for each directory. It then processes each CUE file, checking the mtime to identify if it's been changed. If it's a new CUE file, it tries to load the tracks it references. 

Once all CUE files have been processed, it then checks the files. If a file was handled by the previous CUE check, it will be ignored.

CUE files can also be useful for storing metadata (rather than storing it in the file itself). Though it's main use is accurately describing the layout of a CD (and all of the tracks it contains).

**Comment by ludouzi** [comment]
With https://github.com/fooyin/fooyin/commit/17766af96d7b45974b6fa1b783fc9ecd61a080e1, CUE files are now ignored by default for libraries.

As there haven't been any further updates to this issue, I'll consider it resolved.
