### ISSUE TITLE
PipeWire output is broken

### ISSUE THREAD

**Issue by Pathologic** [fooyin/fooyin#212]
**Describe the bug**
PipeWire output has become broken after some updates: the tracks are playing but with no sound. Alsa output with PipeWire sound server device selected is working. 

**System:**
 - OS: Kubuntu 22.04.4 LTS x86_64 
 - fooyin version: https://github.com/fooyin/fooyin/commit/fa3a34c7e3c2f89a2078d0ae5f58a044607d3d57

**Comment by ludouzi** [comment]
I've managed to reproduce this in an identical system. Looking into it now.

**Comment by ludouzi** [comment]
Looks like I didn't have PipeWire setup in a fresh install; now it's working. If you select the PipeWire output in settings, do you see any devices other than 'Default'?

**Comment by Pathologic** [comment]
Yes, I have all my cards there. But if I start playback all devices disappear.

**Comment by ludouzi** [comment]
How about with https://github.com/fooyin/fooyin/commit/2e6580562c19013ce089a68a8c7957d324686e96?

**Comment by Pathologic** [comment]
It fixes empty devices list. Still no sound anyway.

**Comment by kode54** [comment]
Cannot reproduce on Arch with `pipewire 1:1.2.2-1`.

**Comment by therealfumbles** [comment]
This is happening here too after updating from a few days old build to the latest one.

**Comment by ludouzi** [comment]
I believe this may be caused by changes I made regarding fading. Does adjusting the volume using fooyin's volume controls help?

**Comment by therealfumbles** [comment]
Yep. Moving the slider brings back the audio.

**Comment by ludouzi** [comment]
Great. For PipeWire, fading was previously handled by changing the stream volume, but this caused issues due to too many changes with shorter fade durations. 

After changing this, the volume of the stream was only set once on initialisation. But it looks like setting the volume of a PipeWire application only works consistently when the stream is active, so it was still set to the previous end-of-fade volume of 0.

If you also have fading enabled @Pathologic, this should fix it.

**Comment by therealfumbles** [comment]
Thanks for the quick fix. All good here now!

**Comment by Pathologic** [comment]
Thank you, now it works.
