### ISSUE TITLE
Searching behaves strangely

### ISSUE THREAD

**Issue by CarterLi** [fooyin/fooyin#307]
**Describe the bug**
Both _search in playlist dialog_ and _search in library dialog_ behave strangely. They are opened with no tracks in the list. After typing a character, the titles will show *0 results*. After typing 2 characters, the search results will be displayed.

**To Reproduce**

1. Open the search dialog, no tracks are displayed ![image](https://github.com/user-attachments/assets/0236bdda-d286-403a-9fe2-e8597990e65d)
1. Type one character, still no tracks are displayed. Notably the text `0 results` is shown in dialog title ![image](https://github.com/user-attachments/assets/df757d5c-060f-4ea5-b85d-cf5d5d4df89d)
1. Type another character, it works normally ![image](https://github.com/user-attachments/assets/ac68d5e4-9696-4391-a564-c202bf0deaa1)

**Expected behaviour**
1. Since no search criteria is set, all tracks should be displayed. If one character should be typed at least to trigger the searching, a tip should be added in the list.
1. All matched tracks should be displayed.

**Screenshots**

**System:**
 - OS: Fedora
 - fooyin version: git version

**Additional context**
N/A

**Comment by ludouzi** [comment]
Searching is still a work-in-progress for v0.8.0, so many issues will be resolved over the next few days.

It is intentional that no tracks results are displayed when there is no search term to use for filtering. `ALL` can be used to return all tracks however.

A minimum of two characters for triggering searches was set initially while the query language was being developed. Should performance not be a problem, I may explore allowing searches on one character.

**Comment by CarterLi** [comment]
I suggest adding a tip:

![image](https://github.com/user-attachments/assets/ab28a22e-7a4b-474f-9d4a-4af05b6fbcfa)
