### ISSUE TITLE
Smart playlists / Auto playlists

### ISSUE THREAD

**Issue by vdawg-git** [fooyin/fooyin#374]
I saw that it is on the roadmap.

So I create this issue to get notified when it lands.
I hope this is okay, otherwise just close it instantly

**Comment by AdamAnon** [comment]
Similar question. Do we know when smart playlists are coming? A  music player without smart playlists is useless to me. Fooyin appearance and customization options are great but I need smart playlists. Lack of close equivalent of Music Bee for Linux is literally the #1 reason that keeps me from switching to Linux. Pretty much all Linux music players are abysmal as far as looks, features and customization are concerned. Fooin is the closest I found so far but still no go due to lack of smart playlists. Thanks!

**Comment by ludouzi** [comment]
Initial implementation of smart playlists (autoplaylists in fooyin) is done and will be included in release `v0.9.0` which is planned for release on 2024/11/16: [ROADMAP.md](https://github.com/fooyin/fooyin/blob/master/ROADMAP.md)

**Comment by AdamAnon** [comment]
Great! Thank you :) Looking forward to the update then.
